name: auto deploy CI/CD

on:
  push:
    branches:
      - master
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - LICENSE

jobs:
  build-production:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x] # 配置所需node版本
    steps: # 自动化步骤
      - uses: actions/checkout@v2 # 第一步，检出仓库副本
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }} #规定node.js版本(可不配置)
      - name: Install dependencies # 第二步，安装依赖
        run: npm install
      - name: Build # 第三步，打包代码
        run: npm run build
      # Deploy
      - name: Deploy to Server # 第四步，rsync推送文件
        uses: AEnterprise/rsync-deploy@v1.0 # 使用别人包装好的步骤镜像
        env:
          DEPLOY_KEY: ${{ secrets.ACCESS_TOKEN }} # 引用配置，SSH私钥
          ARGS: -avz --delete --exclude='*.pyc' # rsync参数，排除.pyc文件
          SERVER_PORT: '22' # SSH端口
          FOLDER: ./dist/* # 要推送的文件夹，路径相对于代码仓库的根目录
          SERVER_IP: ${{ secrets.REMOTE_HOST }} # 引用配置，服务器的host名（IP或者域名domain.com）
          USERNAME: ${{ secrets.REMOTE_USER }} # 引用配置，服务器登录名
          SERVER_DESTINATION: ${{ secrets.TARGET }} # 部署到目标文件夹
